package com.tpanh.jobfinder.navigation

enum class JobFinderScreen {
    OnBoarding,
    Login,
    SignUp,
    ForgotPassword,
    ChangePassword,
    Success,
    Verify,
    Home,
    SearchJob,
    JobDescription,
    Filter,
    AddEducation,
    AddSkill,
    AddResume,
    AddWorkExperience,
    UploadCv,
    ViewProfile,
    EditProfile,
    AboutMe,
    Language,
    AddLanguage,
    Setting,
    PostJob,
    SaveJob,
    MyApplications,
    MyApplication,
    Specialization
}